### ISSUE TITLE
Using Components to React Native project

### ISSUE THREAD

**Issue by nipasarker01** [creativetimofficial/light-bootstrap-dashboard-react#14]
Hello,

I want to use this product on a react native project using Expo.How can I incorporate the react dashboard into react native project??

Regards
Nipa

**Comment by EINazare** [comment]
Hello @nipasarker01 ,

Thank you for your interest in using our products.
As of moment we only have Web Templates, and we do not know how mobile frameworks work, which is why we do not have any Mobile Templates.
I'm sorry but we lack in knowledge about Mobile Frameworks and we cannot help you with this.

Best,
Manu

**Comment by cristijora** [comment]
Hi @nipasarker01 
Fundamentally React Web and react native are very different and they share only the "React" library.

What this means is that you write components both in React web and react native but the code is different because those have very different apis and components.
Here is an example

| React Web        | React Native           |
| ------------- |:-------------:|
| div      | View |
| span/p/h | Text |
| button/a | TouchableOpacity/TouchableHighlight/Button|
| localStorage/sessionStorage| AsyncStorage|
| css/styles | StyleSheet (custom Style api) |

There list here is bigger but they idea is that in react native there are different components to build the UI and to access certain mobile features. This means that basically it's very hard to share the same code between web and native and therefore you cannot simply take a web React project and convert it to React Native. 

If you need a React Native kit, I suggest looking at some kits created especially for React Native like those from [Native Base](https://market.nativebase.io/?utm_source=nativebase&utm_medium=showcase+section&utm_campaign=nativebase)

This template will only work on web and could also be ported to a desktop version via Electron and even maybe wrapped in an application with Cordova but will not work in React Native out of the box.

Hope this helps.
