### ISSUE TITLE
TypeError after updating to React 16

### ISSUE THREAD

**Issue by Louventia** [creativetimofficial/light-bootstrap-dashboard-react#16]
<img width="1172" alt="screen shot 2018-04-06 at 10 30 00 am" src="https://user-images.githubusercontent.com/38120930/38401038-ffe1cca8-3985-11e8-9f22-132d189b4dd9.png">

After updating to react 16, I received a lot of errors mainly from the navigation part - Sidebar and Header. And I dont know what to do

I'm doing User Authentication using React.createContext() - https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b. Here's a link about it

Pleas kindly advise >.<

**Comment by EINazare** [comment]
Hello @Louventia ,

And thank you for your interest in using our product.
We are going to make an update to this dashboard next week, maybe Monday or Tuesday, but can not  promise anything. If you want you could wait for our update.
This being said, i've made a quick test by installing react 16 instead fo react 15 (which is in our product), and everything works just fine.
The error you are getting is probably because you do not render the `Sidebar` and `Header` correctly.
The correct code for rendering them is:
```
<Sidebar {...this.props} />
```
```
<Header {...this.props}/>
```
As you can see we are passing `{...this.props}` in both of them because we want to be able to access `this.props.location.pathname` (which is a prop, if i'm not mistaken, that comes from the `Route` in `src/index.js` (see line 24 in this file).
So the `Sidebar` and the `Header` components should somehow be rendered inside a `Route`.
If you do not like this approach (rendering these components inside a `Route`) then you'll have to change every occurrence of `this.props.location.pathname` with another instruction which returns the current link that you have in your browser's input. 
After a quick search on Google i've found that an easy way of getting the same result as we've done in our product is to replace it with `window.location.href`.

Hope this information helps you. Please let me know if i can help you with anything else.

Best,
Manu

**Comment by Louventia** [comment]
Thank for the reply! (/^▽^)/

The Information is really helpful. However I did render the sidebar and header correctly though Σ(-᷅_-᷄๑)

I was thinking I may have run the authentication wrongly. So just to double confirm, May I know where is controller that displays the dashboard? I believe its in the container/App.jsx 
<img width="1130" alt="screen shot 2018-04-06 at 3 42 43 pm" src="https://user-images.githubusercontent.com/38120930/38408687-326e73d0-39b1-11e8-99ff-a97eb9f30d62.png">
^ This part in case there is some misunderstanding

**Comment by EINazare** [comment]
Hello @Louventia ,

You are correct, the dashboard is rendered in `src/containers/App/App.jsx`, through a `Route` component (see line 123).
And you will find the actual page in `src/views/Dashboard/Dashboard.jsx`.

Hope this information helps you. Please let me know if i can help you with anything else.

Best,
Manu
