### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by adriandarian** [creativetimofficial/light-bootstrap-dashboard-react#17]
on this page of your documentation: https://lbd-react.creative-tim.com/#/components#buttons-row
the link is broken for this specific link: https://react-bootstrap.github.io/components.html#buttons-props

You can find it under the props section of the custom buttons

**Comment by EINazare** [comment]
Hello @adriandarian ,

Thank you for your interest in using our product.
We are going to solve this issue in our next update, which will be today or tomorrow.
The problem is that the guys from react-bootstrap have changed their pages and we haven't updated our links to their new website (the updates are actually done - i just need permission to update this product and we are good).
I am sorry for this inconvenience.

Best,
Manu
