### ISSUE TITLE
Unable to npm run build

### ISSUE THREAD

**Issue by Louventia** [creativetimofficial/light-bootstrap-dashboard-react#22]
Hello! As the title said, I am unable to npm run build for it. In fact, it show me this error

<img width="489" alt="screen shot 2018-05-10 at 4 33 44 pm" src="https://user-images.githubusercontent.com/38120930/39860451-f434cacc-546f-11e8-9427-07257552825a.png">

Please advice!

**Comment by Louventia** [comment]
Hi! Sorry for the late reply. I did try to `npm install` before i run the `npm build`. I did changed the font color for the sidebar from a white to a grey

<img width="490" alt="screen shot 2018-05-14 at 9 34 56 am" src="https://user-images.githubusercontent.com/38120930/39974284-3916f2ea-575a-11e8-8a8b-a134898cd265.png">

**Comment by EINazare** [comment]
Hello again @Louventia ,

Well, from what i can see in your image, you have an `EACCES: permission denied`, in your log.
So i think it is kind of obvious what is wrong here. Your machine isn't letting you run the `npm run build` command because you do not have writing permission (when running the build command, it will automatically try to create the `build` folder, and you need to have permission to do so). I want you to understand that this is not an issue with our product.
So the fix is kind of easy, you need to run the command with writing privileges (i.e. `sudo`).

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu

**Comment by Louventia** [comment]
Ok thank you very much!! Now it works!
