### ISSUE TITLE
Whats the difference between layout/view files

### ISSUE THREAD

**Issue by joshueoconnor** [creativetimofficial/light-bootstrap-dashboard-react#24]
Hi,

Whats the difference between the Layout > Dashboard.jsx  and  Views > Dashboard.jsx files? Same question for the Pages components.

Thanks

Josh

**Comment by EINazare** [comment]
Hello @joshueoconnor ,

The difference is that the layout dashboard sets some predefined stuff (such as the navbar, sidebar and footer - meaning that these three components need to be present in almost all of our pages). The same is with the Pages components.
Can i ask you why have you opened this issue here?
It seems to me that you should have opened it [here](https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-react/issues) due to the fact that this is a PRO feature, and not a FREE one.
Where did you get [this link](https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues)?

Best,
Manu
