### ISSUE TITLE
syntax problem in index.js route

### ISSUE THREAD

**Issue by fankoti** [creativetimofficial/light-bootstrap-dashboard-react#29]
Route not have attr "to", maybe need write attr "path"?

**Comment by EINazare** [comment]
Hello @fankoti ,

Thank you for your interest in using our product.
Can you please tell me where do you get this error?
I've just downloaded the product and ran `npm install && npm start` and got not warning.

Best,
Manu

**Comment by jedusaad** [comment]
Hello @EINazare , i think he`s talking about both routers on the product. The one inside the index.js of the application and the other inside the dashboad.jsx layout. Both of them have the <Route > component element as `<Route to={prop.path} component={prop.component} key={key} />` and on the react official documentation they are defined as <Route path="/path" component={prop.component}  />.  I was looking for to switch pages on the index.js page , but anything i`ve done hasn`t worked. O searched the documentation attached to the download, and followed step by step and still nothing. ( my version is the free one ) .
Correct me if i`m wrong, im not able to make this work at index level because you blocked the route/switch there ( i was able to make it work on the dashboard ). That is a feature only on the PRO version! If im wrong i'd like to have an insight on how to make it work, because the steps on the docs about making the switch work on custom pages are the same, just changing the file that is alrered ( for the dasg routes/dashboard.jsx,  for the app routes/index.jsx). 
Thanks for the attantion in advance !\
João Eduardo Saad

**Comment by EINazare** [comment]
Hello there @jedusaad ,

And thank you for your interest in using our product.
I did not understood your question.
Do you want to add a new page inside your app? And you want to add it on a new layout? You do not want to be rendered inside the dashboard route?

Best,
Manu
