### ISSUE TITLE
Consider using functional components?

### ISSUE THREAD

**Issue by cristijora** [creativetimofficial/light-bootstrap-dashboard-react#3]
There are a lot of wrapper components from what I see.
One example is https://github.com/creativetimofficial/light-bootstrap-dashboard-react/blob/master/src/components/StatsCard/StatsCard.jsx

It contains only markup and props which means that it doesn't really have to deal with state.
React devs usually care about this stuff and they transform such components into 
[stateless functions](https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc) because these type of components don't go through the full component life cycle and are more performant

On the other hand the current approach is uniform in terms of code style.

**Comment by EINazare** [comment]
@cristijora thank you for your feedback. On future updates we are going to experiment with stateless functions and we are going to make a decision to what is the best approach (the current one or the one with stateless functions).

Best,

Manu

**Comment by kershnerd** [comment]
Although I am unable to run because of this [https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/6](url), I second this suggestion.  Everyone of your components are classes regardless of whether or not they have state.

Assuming I can build and use your template, I will create a pull request with refactored components.
