### ISSUE TITLE
Feature Request: Removing React-Bootstrap

### ISSUE THREAD

**Issue by Lube** [creativetimofficial/light-bootstrap-dashboard-react#31]
Would it be possible to offer a version without React-Bootstrap. I just find that dependency anoyying when you could implement the same components with bootstrap.

**Comment by EINazare** [comment]
Hello there @Lube ,

Thank you for your interest in using our product.
The thing with react-bootstrap is that it makes a bit easier to render some components.
For example instead of 
`<div className="alert">...</div>`
you would have
`<Alert>...</Alert>`
As you can see, the version with react-bootstrap is a bit smaller in writting.
And this is just a small example.
Another, and the biggest mistake, in using bootstrap directly with react, would mean that you would have to work with jQuery.
And in the React community almost every major player, says that jQuery should not be used with React. The explanation is quite simple, both of these are frameworks over JavaScript, and both of them manipulates the DOM. Let's say for the sake of the argument, it would be almost the same like having React and Vue in the same app, or React with Angular - which is quite obvious that you wouldn't do this.
I hope this will enlighten you a bit and will help you in your development.

Best,
Manu
