### ISSUE TITLE
[Bug] Unrecognized text. Erroneous area: 1: 100% - $sidebar-width

### ISSUE THREAD

**Issue by nishantshah-me** [creativetimofficial/light-bootstrap-dashboard-react#68]
### Version
1.2.0
### Reproduction link
https://jsfiddle.net/
### Operating System
MacOS mojave
### Device
Macbook pro
### Browser & Version
Chrome
### Steps to reproduce
1. npm run-script build
### What is expected?
successfully build
### What is actually happening?
Build failed - Got an error - 
Lexical error on line 1: Unrecognized text.
Erroneous area:
1: 100% - $sidebar-width

---

**Comment by EINazare** [comment]
Hello there, @nishantshah-me ,

Please check one of the following links:
- https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/52#issuecomment-505289309
- https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/50#issuecomment-492533529
- https://github.com/creativetimofficial/light-bootstrap-dashboard-react/pull/64
- https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/62
- https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/53

Please, next time before opening an issue, check if there are not others like your issue.
As you can see, this issue was solved in 5 other Github Issues, there is not point in having a 6th one with the same issue.

Best,
Manu
